### ISSUE TITLE
Architects cutter completely unusable 

### ISSUE THREAD

**Issue by dirtydan116** [ldtteam/Domum-Ornamentum#100]
I crafted an architects cutter and cannot place blocks in it, I am using version 1.19.2 and have my mods loaded through curse forge in the modpack Valhelsia 5. I attempted to use it in a multiplayer server and a singleplayer world and could not place anything into the cutter in either. mods are up to date, is there something i am missing?
thank you

**Comment by MotionlessTrain** [comment]
Update forbidden and arcanus. It was a bug in that mod
