### ISSUE TITLE
Game crashes near DO blocks ->BakedQuad.hasAmbientOcclusion()

### ISSUE THREAD

**Issue by markusvisse** [ldtteam/Domum-Ornamentum#101]
[crash-2022-10-29_11.29.38-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9893350/crash-2022-10-29_11.29.38-client.txt)

Each time I get close to anything related to DO I get a crash. Can't join the server right now as right after logging in I get the crash.

**Comment by MotionlessTrain** [comment]
Remove optifine if you have it. Optifine is not compatible with Domum 
Ornamentum in 1.19. If you want to play with shaders, I recommend rubidium and oculus instead.

**Comment by markusvisse** [comment]
Works for now. Seems that was the problem, thanks for such fast response as the modpack I am using was suggesting Optifine.

**Comment by Raycoms** [comment]
Move to oculus

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by revdave33** [comment]
If you need to stay with Optifine, use forge version 43.1.23 or 43.1.1 (24 made the breaking change) (Saw this on the Optifine issues page)

**Comment by markusvisse** [comment]
Thanks for all the advices. Closing.

**Comment by angeerey** [comment]
This was just fixed in the latest optifine preview (OptiFine HD U I1 pre3): https://optifine.net/downloads
