### ISSUE TITLE
Minor compat bug: Additional Placements (formerly Dynamic Vertical Slabs and stairs)

### ISSUE THREAD

**Issue by The-Professor123** [ldtteam/Domum-Ornamentum#102]
nothing too critical, just needs proper rendering. 
(https://www.curseforge.com/minecraft/mc-mods/additional-placements)

**Comment by marchermans** [comment]
Not sure what exactly you want from us here?

**Comment by The-Professor123** [comment]
ok... one that was really rude, a simple request for more information would've sufficed. two, its just simply applying rendering to the rotations that additional placements provides to stair and slab-type blocks (I.E. your models).

**Comment by Raycoms** [comment]
That might actually not be easily possible. They might be coremodding that into minecraft blocks

**Comment by The-Professor123** [comment]
I don't mean to be rude when I say this: have you looked at it yet, or are you just assuming?

**Comment by The-Professor123** [comment]
i would understand if you did or didn't, i just would like to see these two dynamic mods working together

**Comment by Raycoms** [comment]
If you had given us more info on this, we could more than assume

**Comment by The-Professor123** [comment]
https://www.curseforge.com/minecraft/mc-mods/additional-placements
not much else i can do as a user but this?

**Comment by Raycoms** [comment]
That's just the link to the mod, no description of the issue, no images, no logs, nothing

**Comment by marchermans** [comment]
Given that the OP did not seem to want to spend more then 20 seconds to explain his request and then fact that the linked mod solely relies on Mixins and registry replacements to make this possible i am hereby closing the issue as not implementable.
