### ISSUE TITLE
Materials dont have a "right" tool to harvest it in short time

### ISSUE THREAD

**Issue by f0kx** [ldtteam/Domum-Ornamentum#104]
When i want to break the Blocks of Demum Ornamentum it needs very long to break it.
I have JADE Mod installed and there is no tool i can use for breaking it faster.

**Comment by MotionlessTrain** [comment]
Duplicate of #76 and #60

**Comment by MotionlessTrain** [comment]
The issue is that they are exactly the same block, independent of the materials used to make it. Using a pickaxe is strange for wooden framed blocks, and an axe is strange for stone framed blocks

**Comment by f0kx** [comment]
so breaking a block taking 10 seconds each is solution?

**Comment by MotionlessTrain** [comment]
No, both of the linked issues provide a solution. I just explained the reason of the issue

**Comment by Veranidae** [comment]
it seems the axe is the right tool, at least for the panels. i'm using the one probe and although it _says_ there's no designated tool, when i hold the axe it changes to a check mark and the block seems to break faster
