### ISSUE TITLE
Minecraft Client crash when searching for Glow Ink Sack

### ISSUE THREAD

**Issue by smmmadden** [ldtteam/Domum-Ornamentum#106]
Using the mod version for 1.19.2 on my multiplayer server, I opened search (E) and started typing in Glow Ink Sack...gl and then it crashed the client.  Here is the crash report.  Not clear if this is Domum Ornamentum issue or with REI.
https://pastebin.com/5PikWMUc
Posted on REI Issue page as well: https://github.com/shedaniel/RoughlyEnoughItems/issues/1211#issue-1443824755

**Comment by MotionlessTrain** [comment]
This is an optifine error. Make sure to use an optifine version that is compatible with the forge version you are using, or use rubidium and oculus instead

**Comment by smmmadden** [comment]
I'm using the latest optifine with this OptiFine_1.19.2_HD_U_H9.jar.  Both those mods appear to have other issues with 1.19.2 and full screen support, so not a good replacement IMO.

**Comment by smmmadden** [comment]
I have a dependency to OptiFine as well for a resource pack I'm using, so it isn't an option to switch it out.  Works fine on my other MP Server (not running MineColonies, but MCA).

**Comment by MotionlessTrain** [comment]
That doesn't mean this isn't an optifine issue. They don't support forge rendering, which is needed for more complex rendering (like the build tool preview of Structurize, and the models of Domum Ornamentum).

I haven't heard about any major issues with rubidium and oculus in 1.19.2 fwiw. Mostly people saying that they work better than optifine did

**Comment by smmmadden** [comment]
thanks - if I disable OptiFine search is working, but it breaks the resource pack.  I'm creating issue with OptiFine now. :-)
