### ISSUE TITLE
Crash report with REI

### ISSUE THREAD

**Issue by ChickChuck2** [ldtteam/Domum-Ornamentum#107]
i received a crash report when i search @domum in Search bar on Rei (Roughly Enough Items Forge)

Forge: 1.19.2 : 43.1.47

[crash-2022-11-11_12.27.22-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9991281/crash-2022-11-11_12.27.22-client.txt)

**Comment by MotionlessTrain** [comment]
If you are using optifine, could you try removing it? We recommend rubidium and oculus if you want to use shaders

**Comment by ChickChuck2** [comment]
> If you are using optifine, could you try removing it? We recommend rubidium and oculus if you want to use shaders

is that, i removed the optifine and the error disappear, but i don't use any shaders

**Comment by angeerey** [comment]
This was just fixed in the latest optifine preview (OptiFine HD U I1 pre3): https://optifine.net/downloads
