### ISSUE TITLE
Crafting cheat sheet

### ISSUE THREAD

**Issue by s4sutler100** [ldtteam/Domum-Ornamentum#108]
I'm just looking for a crafting cheat sheet.   Too many  Items that JEI        does  not let me see the recipe.

**Comment by s4sutler100** [comment]
I'm just looking for a crafting cheat sheet. Too many Items that JEI does not let me see the recipe.  
IM using Mine colonies  need to know the recipe to automate roofs.

**Comment by Talyda** [comment]
We tried to help you several times on discord now. If you still don't understand how, then please ask there.  There is no cheat sheet - there is literally *millions* of possible combinations of materials

This page might help:
https://wiki.minecolonies.ldtteam.com/source/dependencies/domumornamentum
