### ISSUE TITLE
Basic blocks don't have loot tables, and some seem to use default block tags/materials

### ISSUE THREAD

**Issue by vectorwing** [ldtteam/Domum-Ornamentum#11]
### Description:

As of version **1.17.1-1.0.10-ALPHA-universal**, certain blocks from Domum Ornamentum seem to lack loot tables, **dropping nothing** when mined. So far, this has only affected the basic blocks (which can be searched with JEI), such as Bricks, Extras, Floating Carpets, and both Barrel orientations. Blocks made in the Architect's Cutter, and the workstation itself, drop normally when mined.

Also, these blocks seem to be using the default Stone sound and `#mineable/pickaxe`, even when the material is meant to be different (Paper, White Paper, Cactus Wood, Wheat etc). The Barrel blocks have this defined correctly.

### Mod List:
Forge 37.0.95
domum_ornamentum-1.17.1-1.0.10-ALPHA-universal.jar

HudCompass-1.17.1-0.2.1.jar
biggerreactors-1.17.1-0.6.0-alpha.6.jar
serverpackutility.jar
InventorySpam-1.17.1-1.4.0.jar
flatbedrock-1.2.0-build.3mc1.17.1.jar
PersistentBits-1.17.1-1.0.jar
jei-1.17.1-8.1.0.26.jar
bambooeverything-1.1.1-build.4+mc1.17.1.jar
modnametooltip-1.17.1-1.17.0.jar
waystones-8.1.3+0.jar
Clumps-forge-1.17.1-7.0.10.jar
journeymap-1.17.1-5.7.3rc3.jar
ElementsOfPower-1.17.1-0.11.0-alpha.jar
SimpleStorageNetwork-1.17.1-1.5.0.jar
phosphophyllite-1.17.1-0.6.0-alpha.6.1.jar
curioofundying-forge-1.17.1-5.3.0.0.jar
charginggadgets-1.4.0-beta.jar
Shrink-1.17.1-1.2.2.jar
Bookshelf-Forge-1.17.1-11.0.3.jar
sophisticatedbackpacks-1.17.1-3.5.2.371.jar
SquatGrow-1.0.1-build.6+mc1.17.1.jar
rare-ice-0.3.0.jar
buildinggadgets-1.17.1-4.0.0-prealpha.jar
biggerutilities-1.17.1-0.0.0-alpha.1.jar
catalogue-1.3.0-1.17.1.jar
balm-1.5.2+0.jar
VTweaks-1.17.1-1.0.jar
PackingTape-1.17.1-0.11.1.jar
mininggadgets-1.9.0-beta.jar
JustEnoughResources-1.17.1-0.13.0.131.jar
cloth-config-5.0.38-forge.jar
forge-1.17.1-37.0.95-universal.jar
absentbydesign-1.17.1-1.5.0.jar
twilightforest-1.17.1-4.0.782-universal.jar
emojiful-1.17.1-3.0.0.jar
ironchest-1.17.1-12.0.2.jar
JAMD-1.3.0-build.14+mc1.17.1.jar
client-1.17.1-20210706.113038-srg.jar
industrial-foregoing-1.17.1-3.3.0.1.jar
FarmersDelight-1.17.1-0.5.0-pre-fc.jar
aequivaleo-1.17.1-0.1.74-ALPHA-universal.jar
vanillaplustools-1.17.1-1.2.jar
torchmaster-3.0.1-beta.jar
theoneprobe-1.17-4.0.2.jar
PlayerPlates-1.0.1-build.9999mc1.17.1.jar
MouseTweaks-2.14-mc1.17.1.jar
ToolBelt-1.17.1-1.17.3.jar
titanium-1.17.1-3.3.0.0-12.jar
enchantingrunes-1.17.1-1.0.0.jar
simplyutilities-1.17.1-0.5.2-build.18.jar
ImmersiveEngineering-1.17.1-5.0.2-pre.232.jar
plaingrinder-1.17.1-1.2.1.jar
similsaxtranstructors-1.17.1-1.0.22.jar
simplylight-1.17.1-1.0.1-build.9.jar
simplybackpacks-1.17.1-1.6.0-build.11.jar
Dimensional-Paintings-1.17.1-1.0.1.jar
SignButton-1.17.1-2.2.2.jar
curios-forge-1.17.1-5.0.1.0.jar
blockui-1.17.1-0.0.26-ALPHA.jar
gravestone-1.17.1-1.0.4.jar
SewingKit-1.17.1-1.4.2.jar
StickyHands-1.17.1-2.0.0.jar
storageracks-1.17.1-1.2.0-universal.jar
angelring-1.17.1-1.4.0.jar
elevatorid-1.17.1-1.8.1.jar
Statues-1.17.1-0.1.7.5.jar
structurize-1.17.1-0.13.253-ALPHA.jar
multi-piston-1.17.1-1.2.1-ALPHA.jar
minecolonies-1.17.1-1.0.43-ALPHA.jar
architectury-2.5.32.jar
appleskin-forge-mc1.17.1-2.1.0.jar
lootr-1.17.1-0.0.9.25.jar
cc-tweaked-1.17.1-1.98.2.jar
Enderthing-1.17.1-1.1.2.jar
moredragoneggs-2.1.jar
modular-routers-1.17.1-8.0.1-72.jar
chiselsandbits-1.1.41-ALPHA.jar
quantumstorage-6.0.0alpha1.jar
Cyclic-1.17.1-1.6.0-OCT17.jar

**Comment by Raycoms** [comment]
Solved, I had a PR open for that for ages, but it wasn't merged yet :derp:
