### ISSUE TITLE
Block{domum_ornamentum:plain} crashes game and my server in 1.19.2 

### ISSUE THREAD

**Issue by ATGLOL** [ldtteam/Domum-Ornamentum#111]
I got this issue from downloading minecolonies with its dependencies (Domum ornamentum being one of them) and when a minecolony load in (the abandon minecolony structure) the game crashes and you cant escape after reloading. to recreate download any version compatible with 1.19.2 and find  the minecolony and game will crash instantly. please let me know if theres a solution to get Block{domum_ornamentum:plain} to not spawn because so far its the only block crashing the game.

**Comment by Talyda** [comment]
If you are using optifine, don't.

**Comment by Talyda** [comment]
If you aren't then you probably want to supply more information, and maybe crash logs etc

**Comment by pouyarisk** [comment]
> If you are using optifine, don't.

I have the same problem with optifine
What if we want to use it?
Or is there any alternative to it?
Or any fix?

**Comment by MotionlessTrain** [comment]
Rubidium and Oculus are (together) an alternative for loading shaders

**Comment by EricTurner3** [comment]
Just wanted to say I was getting "boolean net.minecraft.client.renderer.block.model.BakedQuad.hasAmbientOcclusion()" crashes on certain blocks from this mod. I also had OptiFine, replacing it with Rubidium and Oculus got rid of the issue for me as well. Thanks!
