### ISSUE TITLE
The mod keeps crashing, "Tesselating block model"

### ISSUE THREAD

**Issue by ionng** [ldtteam/Domum-Ornamentum#112]
[crash-2022-11-26_17.24.38-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/10097139/crash-2022-11-26_17.24.38-client.txt)

Here is the txt file for it, not sure why it keeps doing this.

**Comment by MotionlessTrain** [comment]
If you are using optifine, remove it, or update to the latest preview. Optifine hasn't been compatible with forge rendering.
Alternatives are Rubidium and Oculus (the latter is needed for shader support)

**Comment by marchermans** [comment]
This is an error in Optifine
Closing
