### ISSUE TITLE
[Request] Dynmap Support

### ISSUE THREAD

**Issue by xidus90** [ldtteam/Domum-Ornamentum#119]
On our server are all blocks only black on the dynmap.

Can you please add support for it ? https://github.com/webbukkit/dynmap/wiki/Custom-Block-Definitions

**Comment by Moobien** [comment]
> On our server are all blocks only black on the dynmap.
> 
> Can you please add support for it ? https://github.com/webbukkit/dynmap/wiki/Custom-Block-Definitions

RFTools did the same thing back in 1.12.2 for a LOT of blocks, both vanilla and modded. I don't think there is much that can be done, but I could be wrong.  I once had a huge base that had a glass dome over the top, the glass showed as black blocks in the rftools holo projector

**Comment by Thodor12** [comment]
This was still planned from my initial Dynmap compatability PR, however Dynmap hasn't been officially tested outside of my PR yet and we haven't merged this into anything else but 1.18.2 yet.
This is yet to come.

**Comment by ghost** [comment]
Glad to see its coming to 1.19.2 soonish :)

**Comment by marchermans** [comment]
Based on the current stance this will not be implemented anytime soon, and when it likely won't be for 1.19.2.

**Comment by MotionlessTrain** [comment]
~~It has already been implemented in 1.18.2~~

Edit: never mind, this is another feature request than I thought

**Comment by ghost** [comment]
I've done a simple blockscan for dynmap. It helps at least getting the shapes of buildings instead of just invisible blocks. But they are all white which is not ideal. But better than nothing
