### ISSUE TITLE
JEI integration (PLEASE?)

### ISSUE THREAD

**Issue by Talyda** [ldtteam/Domum-Ornamentum#12]
Please can we get some kind of integration with JEI?
People are getting incredibly confused with how to make things and asking on discord multiple times a day.

**Comment by pantsguyapp** [comment]
Speaking of which, what worker will be able to work with the Architect table and auto-craft these blocks in Minecolonies 1.17?

**Comment by Talyda** [comment]
> Speaking of which, what worker will be able to work with the Architect table and auto-craft these blocks in Minecolonies 1.17?

They already do - appropriate worker for the materials used. They have a tab for architect cutter recipes
