### ISSUE TITLE
Framed blocks reverting to a strange wooden texture

### ISSUE THREAD

**Issue by StarkillerRX** [ldtteam/Domum-Ornamentum#121]
For some reason, sometimes, when I reopen a save with DO framed blocks in it, they all revert to a wooden plank texture (dark in the interior, light in he frame). This has happened twice, and the first time I was forced to rebuild the entire village project I was working with. Any solutions?

**Comment by Raycoms** [comment]
Was that from one version to the other?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by MotionlessTrain** [comment]
I believe they contacted on Discord as well, and it turned out it was just a visual thing.
There were a lot of errors on the render thread caused by other mods, it looked like
