### ISSUE TITLE
rendering item

### ISSUE THREAD

**Issue by esthancial** [ldtteam/Domum-Ornamentum#125]
hi, I have a problem when I'm in creative.
When i go to one of the DO categories (the one with the stone cutter looking like) in the creatif inventory, my minecraft crash and close. 
idk if its a problem with the mod or me doing something wrong. 
here is the crash repport 
[crash-2023-02-21_04.48.37-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/10789411/crash-2023-02-21_04.48.37-client.txt)

**Comment by Talyda** [comment]
Remove optifine

**Comment by esthancial** [comment]
> Remove optifine

ty, it worked !!!
