### ISSUE TITLE
Brick/Stone Brick Recipe

### ISSUE THREAD

**Issue by lamppost253** [ldtteam/Domum-Ornamentum#126]
The brick/stone brick variants added by DO are all listed as having incorrect recipes. This includes: brown, beige, cream, and sand bricks. All 8 of these recipes call for 4x of the base material (e.g. terracotta, sand, gravel, and sandstone) instead of the new planned recipes.

**Comment by MotionlessTrain** [comment]
To elaborate: This was found in 1.19.3 on 1.0.82

**Comment by ProsperCraft** [comment]
2x2 sand gives DO bricks making it impossible to craft vanilla sandstone.

**Comment by Raycoms** [comment]
Fix pushed
