### ISSUE TITLE
the framed blocks are invisbile or i rather say that they have water texture

### ISSUE THREAD

**Issue by AmineMoncef** [ldtteam/Domum-Ornamentum#130]

**Comment by MotionlessTrain** [comment]
Are you using graphics improvement mods, and/or shaders?
And which Domum Ornamentum version are you using?

**Comment by AmineMoncef** [comment]
> 

yes i am using patrix resource pack and seus ptgi shaders withe version domum_ornamentum-1.18.2-1.0.77-ALPHA-universal

**Comment by AmineMoncef** [comment]
actually evry item that is crafted using this mode is watery when using this resourcepack and this shader

**Comment by AmineMoncef** [comment]
and also the bottom of the supply ship seems to automatically get destroyed without any reason after a while of placing the ship

**Comment by AmineMoncef** [comment]
> Are you using graphics improvement mods, and/or shaders? And which Domum Ornamentum version are you using?

even if i remove the shaders and the resource pack the items still get a texture of a grid that is colored black and purple

**Comment by MotionlessTrain** [comment]
Are you using optifine to load the shaders, or oculus?

**Comment by AmineMoncef** [comment]
> Are you using optifine to load the shaders, or oculus?

yeh im using the forge optifine version of minecraft

**Comment by Raycoms** [comment]
Yeah, shaders directly detect them as water just because they exist on several render layers

**Comment by AmineMoncef** [comment]
> Yeah, shaders directly detect them as water just because they exist on several render layers

but is their a solution ?

**Comment by Raycoms** [comment]
Maybe @marchermans has an idea, but I believe shaders will have to adjust things for this. Moobien recently talked with a shader dev about this

**Comment by AmineMoncef** [comment]
> Maybe @marchermans has an idea, but I believe shaders will have to adjust things for this. Moobien recently talked with a shader dev about this

ok thx

**Comment by marchermans** [comment]
Yeah not really something we can solve
