### ISSUE TITLE
Extra Brick Shingles Hit Box too short (1.19.2)

### ISSUE THREAD

**Issue by revdave33** [ldtteam/Domum-Ornamentum#133]
domum_ornamentum-1.19-1.0.83-ALPHA-universal

I first noticed it when I had bees stuck on the tops of roofs with brick extra shingles. They would just be flying there. A nudge would get them moving. Then I noticed when I stood on them, I lost part of my feet. When I looked at the shingle, I could see the hut box was only half the height of the displayed shingle.

**Comment by revdave33** [comment]
![2023-03-23_23 07 25](https://user-images.githubusercontent.com/202881/227423685-a064874e-5297-4edd-baae-3c43fc2b9752.png)

**Comment by revdave33** [comment]
![2023-03-23_23 06 31](https://user-images.githubusercontent.com/202881/227423737-9df6fa7f-358f-4640-adda-306306f1f5d0.png)

**Comment by Thodor12** [comment]
This won't be fixed since hitboxes cannot be made to properly follow the exact model shape.
