### ISSUE TITLE
Using smooth stone in the architect's cutter results in a blank, non-existent texture for minecolonies

### ISSUE THREAD

**Issue by TronWoWGamer** [ldtteam/Domum-Ornamentum#135]
I am playing ATM8
When trying to craft items in the architects cutter with smooth stone, the textures are non-existent.  that is, they are blank or see through or something.  there's just no picture at all.  If I make several of something, I can see the count of items, so it's still treating it as a block or tile entity, but there's nothing to see.

Edit:  The missing textures are in the architect's cutter itself when you try and cut blocks though you can see the names of each item as expected, and blank items are tile entities like in your inventory or on minecolonies racks.  Once they are placed in the world, some of them seem to work properly.  The ones I noticed specifically are the round copper pillars.  They have no texture when you are creating them, but when the builders use them in upgrading a building then it seems to work as intended.  This is specifically in the Minecolonies Caldonia building style.

**Comment by TronWoWGamer** [comment]
The same thing exists for blocks of gold.

**Comment by Thodor12** [comment]
Are you using Optifine, if so, you have to remove it

**Comment by marchermans** [comment]
I van not reproduce this on my end

**Comment by vgrynch** [comment]
Same here, though I use a lot of mods. Some of the textures are missing and blocks are invisible. All trapdoors are missing.
