### ISSUE TITLE
Placed your Cobble Roofs with the Building tool , Placed a Clay Roof - Destroys game 

### ISSUE THREAD

**Issue by SamuraiEinhorn** [ldtteam/Domum-Ornamentum#137]
[crash-2023-04-11_22.47.36-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/11204870/crash-2023-04-11_22.47.36-client.txt)

Tryed to place Cooble Roofs - 1 Clay roof spawns , if u touch it , games done - if u Ran over it , Games Crashes too and wont restart

**Comment by MotionlessTrain** [comment]
Duplicate of #136 (Different reason, same crash)
