### ISSUE TITLE
[1.19.4] Framed Pane displays incorrectly

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Domum-Ornamentum#140]
```
Minecraft v1.19.4
Forge v45.0.52
Domum v1.0.88-alpha
```

When placed, the framed pane doesn't display correctly.

![image](https://user-images.githubusercontent.com/12000593/236388921-bd52bd63-ca3b-4861-bd2b-a99b3af54f96.png)

**Comment by dhouck** [comment]
Iʼm getting this too, Minecolonies 1.0.1395-Alpha, DO 1.0.88-ALPHA, no mods not required for either the above (that is, no other mods messing with block rendering) and no resource packs.  This is purely a rendering issue; the block states correctly represent which parts are supposed to exist (or at least which parts are in the blueprint file, but they update appropriately if you add or remove surrounding blocks), and the hitbox and collision box both match the block state.

**Comment by Raycoms** [comment]
Fixed in 1.20
