### ISSUE TITLE
[1.19.4] Crash when blocks placed from creative inventory

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Domum-Ornamentum#141]
```
Minecraft v1.19.4
Forge v45.0.52
Domum v1.0.88-alpha
```

The creative inventory has a few items with duplicated entries, and when the first one is placed, the block immediately causes a crash. 
[Crash Report](https://gist.github.com/WenXin20/b26c67e0fbc49425e9dfe652d2370988)

Blocks with duplicated entries:
- Full Door
- Full Trapdoor
- Full Fancy Door
- Full Fancy Trapdoor
- Full Panel

Both of these have the same id, but one says it has only 1 nbt tag

This one crashes when placed:
![image](https://user-images.githubusercontent.com/12000593/236389741-eb6f5e2a-4231-4752-86a9-90c75510de7b.png)

This one does not:
![image](https://user-images.githubusercontent.com/12000593/236389780-71a02847-0aa4-4c75-bbaa-7d718c3323ba.png)

**Comment by AlexGuignard** [comment]
Any news on this issue ?

**Comment by marchermans** [comment]
Not at the moment.
Hopefully I have time for this next week.
