### ISSUE TITLE
Regular cut copper has only 2 crafting options

### ISSUE THREAD

**Issue by DoctorMage** [ldtteam/Domum-Ornamentum#144]
Forge Version 40.2.0
Mod version : domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar

![image](https://github.com/ldtteam/Domum-Ornamentum/assets/85318453/bb58e247-fd5a-4089-9ba4-faf0cf35e562)
Due to minecolonies requiring cut copper walls it makes a certain build impossible to craft

in game waxed cut copper walls has same options as regular copper walls but regular cut copper walls only has 2 options
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/85318453/ff72fcf0-80e1-4d55-8568-e08c96feda01)
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/85318453/cbeb6758-ef8f-4a26-b37b-5e40f84e6cd2)
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/85318453/acabf810-c767-4e10-8f68-87f5a7aae9da)

**Comment by Talyda** [comment]
Have you tried on most recent version? You're like nearly 30 version numbers out of date

**Comment by DoctorMage** [comment]
Ah that's what curseforge default installed to due to it being set as release my bad

![image](https://github.com/ldtteam/Domum-Ornamentum/assets/85318453/d1311fba-facf-4614-9194-e067237e039b)
still the same with  domum_ornamentum-1.18.2-1.0.77-ALPHA-universal.jar
