### ISSUE TITLE
[1.18.2 Magma Server] Server stops with error message: Encountered an unexpected exception

### ISSUE THREAD

**Issue by xan1mple** [ldtteam/Domum-Ornamentum#145]
[crash-2023-05-25_18.06.13-server.txt](https://github.com/ldtteam/Domum-Ornamentum/files/11563747/crash-2023-05-25_18.06.13-server.txt)
As this file shows,a domum block maybe was placed somewhere,but it was seen as a minecraft chest block entity,causes the game crashed.Is this problem literally CAN'T BE FIX ? I really need to use Magma server.

**Comment by xan1mple** [comment]
The exact location of this Domum block isn't reported in the crashreport,so it can't be deleted by some tool like MCEdit.

**Comment by marchermans** [comment]
No this can not be fixed.
There is a big in one of your plugins or the magma server that causes this.

**Comment by Raycoms** [comment]
Report this to the magma team or plugin.
