### ISSUE TITLE
The problem with shaders

### ISSUE THREAD

**Issue by WeAreNot** [ldtteam/Domum-Ornamentum#146]
Sometimes, when starting the world, with shaders immediately enabled, there is no such problem. But when you disable and re-enable, the textures are displayed incorrectly. This happens with any shaders. At first I thought that the problem was in RAM (lack of it), but as it turned out, this is not the case. The problem occurs only with this mod, other mods that add new current blocks do not have. They either display normally (as needed), or have a sign of a lost texture (purple-black color), or something is wrong with them.

~~I believe that the problem is in the incorrect structure of setting the textures of the mod (since other mods do not have such problems), but again.~~ **These are just guesses. In the form of a solution, I see**: a way that will fix this problem, or the name of the shader, with which there are no problems.

**Comment by marchermans** [comment]
This is not something I can fix. We use the forge model system to perform rendering so i am not sure how to fix this.

**Comment by Nightenom** [comment]
We have/had the same problem in structurize with optifine only, may you try different shader mod?
