### ISSUE TITLE
Placement Preview Rendering

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/Domum-Ornamentum#147]
Preview Placement of blocks (esp panels)

**Comment by AnyankaT** [comment]
I just experienced this - the preview placement for DO blocks - and honestly I hate it. First thing I did was look for how to turn it off. I understand that it's highly requested, but with my particular vision issues it makes it that much harder to see what I'm doing. And the preview persists with a DO block in your hand whether you're placing or not, which I find really annoying.

I'd rather this be something that could be turned off in the config for those who don't want it.
