### ISSUE TITLE
1.19.2 Forge 43.2.0 Issues with ''Effortless Building''

### ISSUE THREAD

**Issue by Totomio** [ldtteam/Domum-Ornamentum#149]
Hi, really nice mod, unfortunatly it don't pair well with effortless building which mess up with the culling face of few blocks like the pillars. How to reproduce, place a pillar no matter the material used, and the top texture will be invisibe/Missing most of the time

![Domum ornamentum - EffortLess Building 1](https://github.com/ldtteam/Domum-Ornamentum/assets/71310604/7a8edf0f-7428-4d12-a296-9f4231993940)

**Comment by marchermans** [comment]
Is effortless building a shader or a mod?

**Comment by Totomio** [comment]
a mod :
https://www.curseforge.com/minecraft/mc-mods/effortless-building/files?version=1.19.2

**Comment by marchermans** [comment]
Can you try to reproduce this please without your shaders?

**Comment by Totomio** [comment]
Yes, here is a screen with Domum-Ornamentum and Effortless Building only,
This glitch seems to be a random thing as you can see one pillar placement is correct, but it's very rare.

![Domum ornamentum - EffortLess Building 2](https://github.com/ldtteam/Domum-Ornamentum/assets/71310604/a86c13bf-45f7-4bb8-8c1d-db91d11b7017)

When I restarted my game and uninstalled EffortLess Building, 2 other pillars found their missing parts but not the others

![Domum ornamentum - EffortLess Building uninstalled 1](https://github.com/ldtteam/Domum-Ornamentum/assets/71310604/ed93cda0-57a5-4c9b-a94b-0024ac61d97f)

**Comment by marchermans** [comment]
Could you please try this with **JUST** vanilla, Domum Ornamentum and Effortless Building?
Cause I can not find a reason for this in any of these.

**Comment by Totomio** [comment]
This is Vanilla, only forge for the mods, i have the same result without the resourcepack.
( I didn't just disable the shader, I also uninstalled rubinium and oculus ).

**Comment by Thodor12** [comment]
Your last image shows expected behaviour, this is just because of culling, we are not rendering the surfaces you normally aren't meant to see, the pillars shouldn't end in an abrupt end of the pillar, always have a cap (like the 1 tall ones do)

**Comment by Raycoms** [comment]
I believe the mod doesnt trigger the player placement methods

**Comment by Totomio** [comment]
The problem may come from the other mod, I don't know. I also opened the issue in the appropriate section for Effortless building
--> https://bitbucket.org/Requios/effortless-building/issues/184/1192-forge-4320-missing-textures-with
