### ISSUE TITLE
Adding mod as a dependency to my project?

### ISSUE THREAD

**Issue by Steferich** [ldtteam/Domum-Ornamentum#156]
Hey,

I'm trying to add this mod as a dependency to my project, but it's not working following the guidelines on this github page.
What I have done is:

added the repository to my settings.gradle file
```
maven {
            name 'LDTTeam - Modding'
            url 'https://ldtteam.jfrog.io/ldtteam/modding/'
        }
```

defined these properties in my gradle.properties file
```
exactMinecraftVersion=1.20.1
domumOrnamentumVersion=1.20-1.0.104-ALPHA
```

and added the dependencies to my build.gradle file:
```
dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly fg.deobf("com.ldtteam:domum-ornamentum:${project.exactMinecraftVersion}-${project.domumOrnamentumVersion}:api")
    runtimeOnly fg.deobf("com.ldtteam:domum-ornamentum:${project.exactMinecraftVersion}-${project.domumOrnamentumVersion}:universal")
}
```

I am getting this error when I reload gradle:
```
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.ldtteam:domum-ornamentum:1.20.1_1.20-1.0.104-ALPHA.
```

What am I doing wrong?
Any help is appreciated, thanks!

**Comment by DancerVlt69** [comment]
The reason is a small issue in the weblink. Type a _ (underscore) instead of a - (minus) between *domum* and *ornamentum*

My solution right now is:
* gradle.properties:
```
DOrnamentumVersion=1.20-1.0.104-ALPHA
```
* build.gradle
```
repositories {

  maven { 
   name = 'LDTTeam - Modding'
   url 'https://ldtteam.jfrog.io/ldtteam/modding/' }
  }
}

dependencies {
   compileOnly fg.deobf("com.ldtteam:domum_ornamentum:${DOrnamentumVersion}:api")
   runtimeOnly fg.deobf("com.ldtteam:domum_ornamentum:${DOrnamentumVersion}:universal")
}
```
And it works fine, almost.

**Comment by Steferich** [comment]
Thanks :) It does work, however I'm getting another error when I try run the task "runData":

```Caused by: java.lang.ClassNotFoundException: com.ldtteam.data.LanguageProvider```

I can _kind of_ get around this by disabling the dependencies whenever I need to generate my data files, however I rather not. Any ideas?

**Comment by Thodor12** [comment]
@Steferich if possible, can you get on our Discord server for Minecolonies https://discord.minecolonies.com, we can help you further there, it's a bit difficult to debug problems like this over a slow chat like issues on Github.
