### ISSUE TITLE
[1.20.1] v1.20-1.0.104-ALPHA crash if I will place a OAK-Trapdoor full in creative mode

### ISSUE THREAD

**Issue by DancerVlt69** [ldtteam/Domum-Ornamentum#157]
Minecraft: 1.20.1
Forge: 47.1.0
ParchmentMC: 2023.07.09-1.20.1
Java: 17.0.7 Oracle OpenJDK
IntelliJ: 2022.3.3 Community

message: 
[Render thread/ERROR] [minecraft/Minecraft]: Unreported exception thrown!
java.lang.IllegalArgumentException: No enum constant com.ldtteam.domumornamentum.block.types.TrapdoorType.
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?] {}

crash-report: https://gist.github.com/DancerVlt69/7024c9d696c93618c509d700c9ca4404

**Comment by Nightenom** [comment]
Fixed in 1.20.4 and newer
