### ISSUE TITLE
(1.20-1.0.104-ALPHA) Crashing every time when using the Architects cutter

### ISSUE THREAD

**Issue by Mazzaradi** [ldtteam/Domum-Ornamentum#159]
As the title says, the game crashes every time I put anything in the architects cutter.

Error Message:
> The game crashed whilst rendering screen
> Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.inventory.Slot.m_6657_()" because "containerScreen.f_97734_" is null

**Comment by Raycoms** [comment]
full log please

**Comment by Mazzaradi** [comment]
https://gist.github.com/Mazzaradi/8eb11d42db1a764d899646d6b743f829

**Comment by Raycoms** [comment]
Is this on a server?

**Comment by Mazzaradi** [comment]
Nope. It was on a single player world

**Comment by Raycoms** [comment]
can you try without AE installed?

**Comment by Mazzaradi** [comment]
Just tried it then without AE. Same thing.

**Comment by Raycoms** [comment]
do you know how to add "-Dmixin.debug.export=true" to the jvm args?

**Comment by Mazzaradi** [comment]
I think so. What would it do?

**Comment by Raycoms** [comment]
It will generate additional log output we can use to analyze what is happening. Some mod is changing vanilla here and we gotta find out how and which =D

**Comment by Mazzaradi** [comment]
I've added the code to the end of the jvm args. What should I do now?

**Comment by Raycoms** [comment]
make it crash again and then send us <.minecraft>/.mixin.out/classes

**Comment by Mazzaradi** [comment]
[mixin.out.zip](https://github.com/ldtteam/Domum-Ornamentum/files/12067110/mixin.out.zip)

I hopefully did it correctly

**Comment by Raycoms** [comment]
Yep, perfect. Its an incompatibility with EquipmentCompare

**Comment by Mazzaradi** [comment]
Huh, yeah. That's done the trick. Never realy used EquipmentCompare so nothing lost XD.

**Comment by someaddons** [comment]
fixed in latest equipment compare
