### ISSUE TITLE
Blocks made with the architects cutter appears translucent

### ISSUE THREAD

**Issue by OccGame** [ldtteam/Domum-Ornamentum#161]
![2023-07-20_08 31 42](https://github.com/ldtteam/Domum-Ornamentum/assets/140011770/511aefe8-f9f2-4864-a4e2-5c910a968fc5)

Only when optifine installed

**Comment by Talyda** [comment]
You're still using some kind of shader/texture pack in that screenshot though?

**Comment by OccGame** [comment]
Yes, i took that screenshot after trying to remove optifine and texture pack. The translucent blocks looks the exact same way even after i removed those.

**Comment by Raycoms** [comment]
This is still with shaders turned on though

**Comment by OccGame** [comment]
Should i repost this without anything else?

**Comment by Raycoms** [comment]
yes

**Comment by OccGame** [comment]
Alright then

**Comment by Raycoms** [comment]
I mean, repost the images =D without the shaders

**Comment by OccGame** [comment]
done !

**Comment by Raycoms** [comment]
and you removed optifine from the mods folder and oculus too?

**Comment by OccGame** [comment]
Yes ! I don't have oculus tho

**Comment by Raycoms** [comment]
Can you send us your log?

**Comment by OccGame** [comment]
I'm not sure if you need the full log or not

**Comment by Talyda** [comment]
That still shows optifine installed in that log.
And you're using 1.18.2?

**Comment by OccGame** [comment]
I had optfine removed, so i don't know why it's showing. And yes, i'm on 1.18.2

**Comment by OccGame** [comment]
I'll send the logs from when i had it removed instead, maybe it's showing on the latest log because i played again

**Comment by OccGame** [comment]
Nevermind, i didn't see the "preview optifine" file in the mod folder... so optifine is the problem, 
![2023-07-21_00 30 25](https://github.com/ldtteam/Domum-Ornamentum/assets/140011770/1bd55f80-d30f-42de-bd02-a8c73bb71b91)
