### ISSUE TITLE
Crashed mining a panel

### ISSUE THREAD

**Issue by vulgarfatetoo** [ldtteam/Domum-Ornamentum#162]
Playing the MineColonies Official Modpack 2.3 with some added mods:
- Tom's Simple Storage Mod
- Refined Storage (that I keep meaning to remove lol)
- Carry On
- Catalogue
- updated JEI (compared to the version in the modpack)
- More Overlays Updated
- Elevator Mod
- Just Enough Resources
- Nature's Compass
- Simple Quarry
- Waystones
- Explorer's Compass

Hopefully the list helps instead of comparing between official + what's listed in my crash log :P

I was mining a Panel Full (Spruce Planks) type from a ceiling and it crashed; I'm unsure if Domum Ornamentum is the cause, but it is on the first line, and y'all are Minecolonies pack creators also. MCLogs [here](https://mclo.gs/Wr2X471)
After reloading back into the world, I mined the block with no problems. Let me know if you need anything else from me

**Comment by Raycoms** [comment]
Are you on the latest?

**Comment by Raycoms** [comment]
Ah, this is on 1.19

**Comment by vulgarfatetoo** [comment]
Oop added a mod to the list I forgot. Yis I'm using the Curseforge Launcher, it lists the latest release of Minecolonies Official modpack being 2.3 on 16 July n.n:
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/138251317/a5137cd2-7919-427e-8cf8-19988ed73a8c)

**Comment by Raycoms** [comment]
Can you try with the 111 beta?

**Comment by vulgarfatetoo** [comment]
BOLLocks sorry I went to sleep then had a Sims day yday haha, I haven't been able to recreate the crash, been mining panels in the same place for a little while now, but I'll try 111 all the same! Wanted to report the crash at least just in case it helps with anything n.n

**Comment by Raycoms** [comment]
:+1:
