### ISSUE TITLE
Reclaiming/Harvesting with pickaxe no item?

### ISSUE THREAD

**Issue by Cursedth** [ldtteam/Domum-Ornamentum#163]
Minecraft : 1.20.1
Version : 1.0.110
Forge : 47.1.0

Not sure if it is a bug or intended.

I have JEI, but not something as Jade or Waila. 
Still kinda new to the game, but not to modding or coding.

Found out while getting some copper posts back you don't get the items back
when you use a pickaxe and and axe was needed? 
I lost some pieces and had no idea (searching everywhere)
The pick axe breaks them really fast though and takes ages with an axe.

Shouldn't it be:
-It takes longer if you use the wrong tool for it but you still get it back as an item drop.
-Using the correct tool just mines it faster. 

But a copper post isn't a diamond block right?

I thought I should mention it. 

Regards,

**Comment by aAndrew3030** [comment]
I can confirm, blocks crafted in the cutter are set to drop with a axe, but block durability is set to break with a pickaxe

**Comment by aAndrew3030** [comment]
Blocks have the mineable/axe tag, but mine very slow

**Comment by trevorjd** [comment]
Tested just now with domum_ornamentum-1.19-1.0.146-BETA-universal in isolation (no other mods, not even JEI)

Beige brick and brown brick slabs created in the cutter.

Harvest with a pick is fast but drops no item

Harvest with an axe is slow (like you'd expect the item to be destroyed) but drops the item OK.

**Comment by Graffitoz** [comment]
Omni tools (like Paxels) can avoid this issue (they have all 3 tags) while we wait for an actual fix.
F3 shows that the blocks only have "minecraft:mineable/axe" regardless of block data, so perhaps an easy fix could be to add the remaining tags.
