### ISSUE TITLE
Crash when trying to place "Fancy Oak Door"

### ISSUE THREAD

**Issue by jouki** [ldtteam/Domum-Ornamentum#165]
got a crash on the client side (single-player, creative).

Here's the log: https://gist.github.com/jouki/97128160b8e094718d17185cb1e12325

Cheers,
Jouki

**Comment by Raycoms** [comment]
Is there a way to reproduce this?

**Comment by jouki** [comment]
Unfortunately, since it was creative I don't remember the combination because the item was rotating the combinations.

Regardless of the combination, I was just placing "Fancy Oak Planks Door" Variant "Full"

**Comment by Raycoms** [comment]
fixed
