### ISSUE TITLE
Builder's Scroll UI for Shingle Materials Broken

### ISSUE THREAD

**Issue by gr2ws** [ldtteam/Domum-Ornamentum#166]
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/96656463/4d9f2365-36cc-4b49-bf0e-2d34d6120be2)

Version: domum_ornamentum-1.20-1.0.122-BETA-universal
I cannot craft the correct shingle types because the materials are not displayed due to this bug.

**Comment by Raycoms** [comment]
fixed
