### ISSUE TITLE
Trapdoors become Creative Item

### ISSUE THREAD

**Issue by bearsjunior** [ldtteam/Domum-Ornamentum#17]
When placing down Trapdoors they become the Creative Item instead of the material i made them out of, Fancy Trapdoors are working though,
i am on 1.18-1.0.31-ALPHA with Minecolonies, Create, and JEI plus the required mods for them

**Comment by VolcanicMG** [comment]
I am also on the same version and getting the exact same issue. Nice item frame item at least.

**Comment by Talyda** [comment]
Yeah, adding to this, similar problem here

Using .31 - if I make dark oak trapdoors, the fancy ones work, but the regular ones when I place them, turn into oak planks trapdoors, then if I middle click to add them to my tool bar to see if they stay as oak plank trapdoors, they turn into the creative item, scrolling through all the possible combinations of materials =)

I downgraded to .28 and they worked fine

**Comment by VolcanicMG** [comment]
> Yeah, adding to this, similar problem here
> 
> Using .31 - if I make dark oak trapdoors, the fancy ones work, but the regular ones when I place them, turn into oak planks trapdoors, then if I middle click to add them to my tool bar to see if they stay as oak plank trapdoors, they turn into the creative item, scrolling through all the possible combinations of materials =)
> 
> I downgraded to .28 and they worked fine

It probably just one bit of code that got changed or removed. Wish In knew more about minecraft modded because I wouldn't mind looking into the issue. I want to make custom trap doors for my super secret spots hehe.
