### ISSUE TITLE
Current (domum_ornamentum-1.20-1.0.110-RELEASE-universal.jar) is not interactable

### ISSUE THREAD

**Issue by SenpaiDerp** [ldtteam/Domum-Ornamentum#171]
Hello!

On the modpack MineColonies Dimensional Adventure, this mod is heavily used. As of this update, when the architecture table is interacted with, it does not allow placing materials in the table. When using JEI to check recipes, it shows no input for any recipe or, if it does, no output for ones that can be input (i.e. it says you can put in glowstone but that there is no output).

The pack dev is aware and stated that they are waiting on this mod to update. I did not see this issue reported so I wanted to add it.

**Comment by MotionlessTrain** [comment]
This seems to be an issue with Epic Paladins. They are aware of the issue
