### ISSUE TITLE
Domum Ornamentum - Door Dupe Glitch

### ISSUE THREAD

**Issue by iShockGIT** [ldtteam/Domum-Ornamentum#176]
So I made a fancy door in the saw table thing. I misplaced the door, so I took it down and 2 dropped instead of 1. I don't know if this is intended, but I don't think it is. 2 doors drop out of 1 door.

https://www.youtube.com/watch?v=TO2WxKbg4mU

Version used:
**domum_ornamentum-1.19-1.0.130-BETA-universal.jar**

**Comment by iShockGIT** [comment]
Almost forgot to mention that I'm using
domum_ornamentum-1.19-1.0.130-BETA-universal.jar

**Comment by AlisonHuang777** [comment]
Same here. Playing Prominence II [FORGE] v1.3.6 modpack which contains **domum_ornamentum-1.20-1.0.129-BETA-universal.jar**.
