### ISSUE TITLE
Optifine - Purple and Black Textures

### ISSUE THREAD

**Issue by HelixCreations** [ldtteam/Domum-Ornamentum#18]
I am using your mod with Optifine however the models are coming up as Purple and Black. Would this be an Optifine issue or your mod issue? I have read that Optifine reads textures differently than Vanilla.

**Details**
Minecraft 1.18.1
Forge 39.0.8
Optfine HD U H4
No texture packs.

![javaw_9Dwilip0xg](https://user-images.githubusercontent.com/54270298/147378723-61a72ba7-cfab-4d0b-9b11-c3481b04f1d5.jpg)
 
Thanks.

**Comment by Raycoms** [comment]
That's due to a lack of support of optifine of the forge rendering pipeline. Please report this to optifine directly.

**Comment by Crowlord** [comment]
I have found that the BSL Shaders seem fine. Perhaps its the shader pack?

**Comment by FoolishSamuraii** [comment]
> 

I'm trying BSL Shader now and still seeing the same issue. Can you post what settings you had, resource packs, mods, etc etc?

**Comment by Crowlord** [comment]
I have moved away from this pack but using shaders just fine on my new server. 

I have found that the textures are initially broken but fix after a restart of the client!
