### ISSUE TITLE
Architects Cutter ignores variant

### ISSUE THREAD

**Issue by sieuwe** [ldtteam/Domum-Ornamentum#184]
When crafting a trapdoor or plank style variant, the first boss variant is crafted.
Even when choosing a different variant, the boss variant or first in the list will still be crafted.
This happens on the oak planks trapdoor for example.
In addition, the bottom slot stays red and you can't insert any type of material, don't know if that's intended.

**Comment by sieuwe** [comment]
![2023-10-16_19 44 10](https://github.com/ldtteam/Domum-Ornamentum/assets/1788082/1875cbe1-1f92-488a-928e-3a7df5b221c1)

**Comment by Raycoms** [comment]
Yeah, I derped, on it

**Comment by Raycoms** [comment]
fix merged
