### ISSUE TITLE
Cannot craft any panel variants other than Boss.

### ISSUE THREAD

**Issue by Axyl69** [ldtteam/Domum-Ornamentum#185]
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/69871266/40f4ede8-9dde-48fc-8d34-18b76c5087a5)
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/69871266/1d1fa407-a07e-43e6-8018-e165a6cfa432)

When trying to craft any variant of panel with any material, the result is always Boss as shown in the images.

The version I am using is:
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/69871266/2280609f-a1bb-4f99-ac6f-637d8c688e53)
This is the current version that is in All The Mods 9

Is there a way to /give specific variants/materials for the meantime?

**Comment by MotionlessTrain** [comment]
Could you try upgrading to 1.0.139? This should just have been fixed
