### ISSUE TITLE
Game Crash from breaking block

### ISSUE THREAD

**Issue by WillowWhispers** [ldtteam/Domum-Ornamentum#186]
When I try to break the misplaced shingles, which is made out of cobbled deepslate both the main material and the supported by material, it crashes my game.

It gave me a nullpointerexception.
[crash-2023-10-19_18.09.21-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/13048158/crash-2023-10-19_18.09.21-client.txt)

Here is the crash report provided by minecraft. I am using Forge in version 1.20.1. No optifine.

**Comment by Raycoms** [comment]
Update, fixed in newest
