### ISSUE TITLE
DO blocks can't be mined/ tool choice is non-intuitive

### ISSUE THREAD

**Issue by kezmodius** [ldtteam/Domum-Ornamentum#187]
![2023-10-21_13 24 36](https://github.com/ldtteam/Domum-Ornamentum/assets/120763436/94decf16-8b2d-4178-9b2d-1b7443f3fef8)
![2023-10-21_13 24 45](https://github.com/ldtteam/Domum-Ornamentum/assets/120763436/115eef4e-3a08-44f8-8f08-174d5357ca84)
This wall needs a pickaxe to mine (ok, understandable if the original is a stone item), but the framed sea lantern is unrecoverable with all tools. I tried hand, axe, pickaxe. silk touch pick axe, sword and hoe.

**Comment by Raycoms** [comment]
We cant do anything about the unintuitive thing, as we cant make this more flexible unfortunately. But I fixed the lights now to also use the axe
