### ISSUE TITLE
cutter dose not work with any blocks.

### ISSUE THREAD

**Issue by AnakaiTenshi** [ldtteam/Domum-Ornamentum#189]
1.20.1 mod version 1.0.144 is broke shows nothing has 1 screen of only oak variants and will not accept any blocks to cut period. can not even put anything into the gui are you working on this or is this mod dead?

**Comment by Talyda** [comment]
Working fine for me

**Comment by Raycoms** [comment]
did you try to click on the blocks in the screen?

**Comment by MotionlessTrain** [comment]
Do you perhaps have Epic Paladins installed?

**Comment by AnakaiTenshi** [comment]
> Do you perhaps have Epic Paladins installed?

Yes I do is that the problem?

**Comment by AnakaiTenshi** [comment]
> did you try to click on the blocks in the screen?

yes clicked them they still would not take any blocks to craft with.

**Comment by MotionlessTrain** [comment]
> > Do you perhaps have Epic Paladins installed?
> 
> Yes I do is that the problem?

Epic paladins has prevented items from being placed into the architect's cutter before

**Comment by AnakaiTenshi** [comment]
> > > Do you perhaps have Epic Paladins installed?
> > 
> > 
> > Yes I do is that the problem?
> 
> Epic paladins has prevented items from being placed into the architect's cutter before

Removed it and fixed the issue thank you! really liked epic paladins to kinda sucks. I wish forge would add a conflict tagger on mods for people to report these right on the mod page to warn others.
