### ISSUE TITLE
Missing items to craft in Cutter

### ISSUE THREAD

**Issue by CloWnicide** [ldtteam/Domum-Ornamentum#195]
Trying to upgrade buildings, but the required item is missing from the cutter. Unless the only way to make these is with the villagers themselves?

![image](https://github.com/ldtteam/Domum-Ornamentum/assets/27911500/e2189c92-e87e-4dc5-8610-ce947d4b258a)

**Comment by Raycoms** [comment]
Remove the epic paladins mod

**Comment by CloWnicide** [comment]
Don't have it installed

**Comment by CloWnicide** [comment]
Can I  get any assistance with this? You replied with an answer that does not pertain to my issue, immediately closed the topic and have not responded to my other comment.

**Comment by Talyda** [comment]
Tried a binary search to work out which mod is causing the problem?

You can try a binary search
The **binary search** is a way of finding a faulty thing among a lot of other things without having to remove the things one-by-one.

This is useful for finding a broken mod among hundreds of mods without having to spend time testing the mods one-by-one.

The procedure is simple:
1. Remove half of the existing things, and put them aside.
2. Run the program / game.
3. Does the issue still exist?
  - If **YES**: Repeat from step 1 with the current things.
  - If **NO**: Swap out the current things with the ones set aside, and repeat from step 1.
4. Repeat this process until the problematic thing(s) have been found.

**Comment by Raycoms** [comment]
There are 2-3 mods that interfere with block mods like DO. Diagonal Fences, Epic Paladins are two of them, else you might have to try binary
