### ISSUE TITLE
[BUG] Architect's Cutter - Fences

### ISSUE THREAD

**Issue by Build3000** [ldtteam/Domum-Ornamentum#196]
Versions:
Minecraft 1.20.1
Domum Ornamentum 1.20-1.0.147-BETA
Forge 47.2.0

Issue:
Missing recipe Architect's Cutter for Vanilla Fences

Description:
Minecolonies requires "Spruce Log Fence" to be made with the Architect's Cutter, however the group "Vanilla Blocks" only contains "Fence Gate", "Slab", "Wall" and "Stairs".

**Comment by Talyda** [comment]
You have a mod called diagonal fences? That removes the fences from the cutter for some reason

**Comment by Build3000** [comment]
Yes I do.
Didn't consider the diagonal fence Mod to delete the recipes on the Architect's Cutter somehow.
Disabling the mod fixed the issue.

Thank you for your help.

**Comment by koledadavid08-glitch** [comment]
the architect's table doesn't work, and when I check the recipes in Jay, I see a broken interface, and the blocks don't fit in any way  

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/f8beafec-c3e2-4cfc-be25-f3dacd42487b" />

**Comment by AnyankaT** [comment]
> the architect's table doesn't work, and when I check the recipes in Jay, I see a broken interface, and the blocks don't fit in any way
> 
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/263325236/556574111-f8beafec-c3e2-4cfc-be25-f3dacd42487b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzIzODAyOTEsIm5iZiI6MTc3MjM3OTk5MSwicGF0aCI6Ii8yNjMzMjUyMzYvNTU2NTc0MTExLWY4YmVhZmVjLWMzZTItNGNmYy1iZTI1LWYzZGFjZDQyNDg3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMwMVQxNTQ2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjlhOTE3MTJjYzUyN2I2YmYwYzVkNDFkMDcwZjhjNjZjOTExMjRkZTRiYWUzZDI5YWI0MmY4YjA5MGI5YWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qYGbvpeE67BWOb4v85jOm1XMK4aOLFxdGKy22XKTeQQ">

Any of these mods included in your pack? 

**Currently known incompatibilities for Domum Ornamentum.**

- Palladium - renders architect cutter blocks weirdly, using the wrong textures
- Xycraft Overrides - makes the buttons invisible when you try to make a block from glass
- Spooky Structures - prevents architect's cutter functioning
- Continuity - causes some architect's cutter block icons to be invisible
- Hoarding - causes some blocks to not be craftable in the architect’s cutter
- VMinus - prevents architect's cutter functioning
- Carryon - picking up a DO block with Carryon will crash your game and possibly lock you out of logging back in
