### ISSUE TITLE
Missing recipe for variants of Vanilla fences in the Architect's Cutter.

### ISSUE THREAD

**Issue by GomatiGit** [ldtteam/Domum-Ornamentum#198]
The group "Vanilla Blocks" only shows Fence Gates, Slabs, Walls and Stairs.

The recipes of fences are missing in the group Vanilla Blocks as variant of the Architects Cutter.
Those Items are requested for some designs to build like "Caledonia"
![architectscutter](https://github.com/ldtteam/Domum-Ornamentum/assets/98549811/cd6454e9-2b67-4648-b496-2a9014579f5b)
It only shows fence gate, slabs, walls, stairs.
Version 1.20-1.0.147-BETA
Forge: 47.2.6
Game Version 1.20.1

**Comment by Talyda** [comment]
Diagonal fences makes that category disappear. Diagonal windows, which you might also have installed, makes teh paper walls disappear

**Comment by GomatiGit** [comment]
You are correct. We also use Diagonal fences on our server. It seems this issue is also a known bug. It was already opened here https://github.com/Fuzss/diagonalfences/issues/9
thanks for clarify
