### ISSUE TITLE
Architect Cutter no displaying vertical panel catagory

### ISSUE THREAD

**Issue by thepriz** [ldtteam/Domum-Ornamentum#200]
Forge Version: 43.3.2
Domum Ornamentum Version: 1.19-1.0.146-BETA

The vertical panels are not being displayed as a category or in the Paperwalls in the Architect Cutter. I think I was able to craft them once then they disappeared from the list at some point.
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/34556672/151f7b82-d412-4eb4-bd26-677f3650c65a)

**Comment by Thodor12** [comment]
"Vertical panels" are not a separate thing, they are just panels. You can place panels vertically against any surface.

**Comment by thepriz** [comment]
I swear that I saw a request from one of my villagers for a vertical variant. Old age is kicking in I guess.

**Comment by Thodor12** [comment]
That might've been a paper wall then, or that was from previous versions where Domum did not exist yet, and we had some fixed models in Minecolonise itself.
