### ISSUE TITLE
Game Crash When Breaking Blocks

### ISSUE THREAD

**Issue by InfinityGaben** [ldtteam/Domum-Ornamentum#201]
When you break the modded blocks while crouched it crashes your game, so far ive seen and had it happen with framed wool.

**Comment by Raycoms** [comment]
Can you send us your crash log please?

**Comment by InfinityGaben** [comment]
[crash-2023-11-24_00.23.11-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/13457750/crash-2023-11-24_00.23.11-client.txt)

**Comment by Thodor12** [comment]
Update your mod, 110 release is quite old by now and this nullpointer is already fixed from what I can tell

**Comment by InfinityGaben** [comment]
cant wait to tell my friends that decided to merge 2 packs that they didnt have a up to date version of this
