### ISSUE TITLE
1.0.153 Beta crashes on server.

### ISSUE THREAD

**Issue by DelviousCrafts** [ldtteam/Domum-Ornamentum#217]
Latest version of Domum attempts to load Client only class on server causing a crash. Does not affect single player.

[crash report](https://gist.github.com/DelviousCrafts/0359b8ae7345a54e905e038ab5ca3918)
[latest log](https://gist.github.com/DelviousCrafts/529f840bae90418a3cb61d01e1673f14)

versions: 
- Minecraft: 1.20.1
- Forge: 47.2.20
- Domum Ornamentum: 1.0.153-Beta

**Comment by Raycoms** [comment]
Fixed
