### ISSUE TITLE
Cannot launch with forge 0.19

### ISSUE THREAD

**Issue by itsdinkd** [ldtteam/Domum-Ornamentum#22]
crashing when launching
```java
net.minecraftforge.fml.ModLoadingException: Mod §eminecolonies§r requires §6domum_ornamentum§r §o1.18-1.0.33-ALPHA or above§r
§7Currently, §6domum_ornamentum§r§7 is §o1.18-1.0.32-ALPHA
```
however, 

![image](https://user-images.githubusercontent.com/35115304/149403727-f71676d5-9f3d-4a0c-9481-a0cb16e018cf.png)
![image](https://user-images.githubusercontent.com/35115304/149403739-bba89f88-3bea-466a-b8f9-43de7985c615.png)

**Comment by Raycoms** [comment]
This one: https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum/files/3602029 ?

**Comment by itsdinkd** [comment]
shit i read the error wrong. for some reason I thought it was complaining about the modloader version
