### ISSUE TITLE
inventory item not shown

### ISSUE THREAD

**Issue by roeeNavonPrivate** [ldtteam/Domum-Ornamentum#220]
i am using mcreator to make a mod that addes some blocks, and i am trying to add support for DO using the tags. it is working, when i place the it visible and textured correctly, yet the item in the inventory is invisible. here is some photos:
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/107650855/61698df1-f8fb-4858-ab8d-b50010afd968)
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/107650855/13466420-91c6-44be-80af-e6779e50a7bd)

**Comment by Raycoms** [comment]
@marchermans any clue?

**Comment by roeeNavonPrivate** [comment]
Is there is a better place to ask this question?

**Comment by marchermans** [comment]
Generally this means that the model for the Block in the inventory is structured weirdly and is not compatible.

**Comment by roeeNavonPrivate** [comment]
i light of what you have said i think that i found the problem, I would be happy if you will confirm it.
this is the json file of the block model of an example block from my mod:
`{
  "parent": "block/cube",
  "textures": {
    "down": "roees_utils:block/blue_pastel_bricks",
    "up": "roees_utils:block/blue_pastel_bricks",
    "north": "roees_utils:block/blue_pastel_bricks",
    "east": "roees_utils:block/blue_pastel_bricks",
    "south": "roees_utils:block/blue_pastel_bricks",
    "west": "roees_utils:block/blue_pastel_bricks",
    "particle": "roees_utils:block/blue_pastel_bricks"
  },
  "render_type": "solid"
}`
i checked against vanilla minecraft and the parent tag there is minecraft:block/cube_all.
in any case i am also adding here the item model json, in case i am wrong at my eypotesis: 
`{
  "parent": "roees_utils:block/blue_pastel_bricks",
  "display": {
    "thirdperson": {
      "rotation": [
        10,
        -45,
        170
      ],
      "translation": [
        0,
        1.5,
        -2.75
      ],
      "scale": [
        0.375,
        0.375,
        0.375
      ]
    }
  }
}`
