### ISSUE TITLE
Effortless building corrupts blocks from this mod

### ISSUE THREAD

**Issue by DereC4** [ldtteam/Domum-Ornamentum#222]
Attempting to place blocks with effortless building for some reason reverts blocks from this mod into a block that randomly changes material every tick. 

https://youtu.be/AwM8KMtajkA

I showcased the problems here if you want to take a look

**Comment by marchermans** [comment]
Please report this to Effortless Building.
We simply hold data on the ItemStack that we set when the player places the block down on the BE.
Effortless building likely breaks that interaction.
