### ISSUE TITLE
Was playing minecolonies and gave myself a panel then the game crashed

### ISSUE THREAD

**Issue by Jrolon81** [ldtteam/Domum-Ornamentum#234]
[Uploading latest.log…]()

**Comment by Jrolon81** [comment]
[latest.log](https://github.com/ldtteam/Domum-Ornamentum/files/15141869/latest.log)

**Comment by Thodor12** [comment]
How did you create the panel

**Comment by Thodor12** [comment]
By the looks you used the `/give` command, because the block is spitting errors it's missing data without a name.

You should make Domum blocks using the Architects cutter, where you have to create it by putting in several blocks and choose what block to create.

This issue can be closed.
