### ISSUE TITLE
Flat shingle stripes

### ISSUE THREAD

**Issue by AkGamerRo** [ldtteam/Domum-Ornamentum#239]
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/46200199/13474db4-1c42-41de-a2b4-51cf6b0f6920)
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/46200199/65ff870b-968e-47e0-b008-22c7a0ca4fd3)

Result of alternating flat shingles (both lower and normal).

Block model seems off: shingle extension slightly higher than rest of the block resulting in stripes where (I would assume) should not be.

version: domum_ornamentum-1.20.1-1.0.187-BETA-universal

I want to add the fact that I want this to function as both bug report and suggestion.
What this post wishes to accomplish:
1. Fixing the normal flat shingles. (the bug part)
2. Adding a new set of shingles that has the extension slightly bigger to make the stripes consistent top to bottom. (the suggestion part)

**Comment by AkGamerRo** [comment]
I want to add the fact that I want this to function as both bug report and suggestion.

**Comment by Talyda** [comment]
I went and had a look at the models, cos AkGamer said it didn't happen with the regular shingles.
Regular shingles, the end parts (the overhang) is 0.1smaller/shorter than the middle part of the model, you can see it here (barely, it is very small LOL!) 
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/17323101/d98dd448-b626-4fdc-b06d-41881b184849)

The flatter shingles, are 0.05 higher on the ends/overhang than the middle bit
![image](https://github.com/ldtteam/Domum-Ornamentum/assets/17323101/90ca3bfa-4fa9-4f81-ab87-d64aacd85d57)
