### ISSUE TITLE
1.0.33 is only tagged on Curseforge as 1.18 - not 1.18.1

### ISSUE THREAD

**Issue by superninjakiwi** [ldtteam/Domum-Ornamentum#24]
Files that are tagged as compatible with 1.18 and not 1.18.1 will not be shown in 3rd-party clients that access the Curseforge API to download mods for 1.18.1 instances, such as ATLauncher, where only 1.0.31 and 1.0.32 are visible. As newer versions of Minecolonies require 1.0.33 this is a minor inconvenience for anyone who updates primarily via launcher. 

If Curseforge makes it too much of a hassle to update the file's tags, then it should be fine to just wait till the next version released to tag it with 1.18.1, and have people download the current new version manually if they care that much.

**Comment by marchermans** [comment]
Fixed in a new release.
