### ISSUE TITLE
[Bug] Broken textures on Shingles in Ancient Athens buildings

### ISSUE THREAD

**Issue by hehehe426** [ldtteam/Domum-Ornamentum#248]
![image](https://github.com/user-attachments/assets/f31cfbd5-7149-4c18-9891-c618f588583b)

I am seeing broken textures on shingle corner placements in some Ancient Athens buildings, including villa residence level 3, tavern level 2, and university level 2. Shindria on Discord confirmed the issue was visible in her game also.

**Comment by Thodor12** [comment]
What version is this happening on

**Comment by Talyda** [comment]
The newest DO (the one with teh shingle texture changes) .190
