### ISSUE TITLE
Architects cutter inconsistency 

### ISSUE THREAD

**Issue by SivartMcDorf** [ldtteam/Domum-Ornamentum#25]
### Prerequisites 

- [ ] I am running the latest **alpha** version of Structurize for my Minecraft version.
- [x] I checked the MineColonies/Structurize [wiki](https://wiki.minecolonies.ldtteam.com/) and made sure that my issue is not covered there.
- [x] I made sure that **this change request is not a duplicate of any existing change request.**

### Context 

- Minecraft Version:
- Structurize Version:

## Is your feature request related to a problem?
the architect's cutter is very confusing.  When hovering over a recipe it says for example:

Brick Extra Shingles
Supported By Acacia Planks
Covered by Brick Extra
Supported by Brick Extra

but on the architect cutter it goes
Brick extra       Acacia plank
Brick extra

and none of the blocks on the architect cutter is labeled

in the carpenter shop, it is 
Input 1
input 2
input 3

This is very unclear and confusing and there is no consistency.  In support, I was told to just keep trying until it works.  That is a stupid answer.

## Enhancement or Change description
Need to use a standard configuration/language across all inputs.
suggest all be labelled the same and arrange the blocks on architect cutter in the same configuration so that when you right down ingredients 1,2,3 that in every possible place to put them in they are put in 1,2,3 in the same arrangement

### Notes or related things
I really hate this new system, I know it adds a lot of flexibility but the implementation seems to be very poorly planned with no guide put out and inputs that don't make sense.  I have been having to explain it over and over again to people on my server and I don't even really understand it.  

---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by uecasm** [comment]
If it's a space issue, maybe each slot could show a different icon next to it, and the tooltip could show the matching icons too?  Or the tooltip could show the item icons in approximately the same layout as the cutter.

**Comment by marchermans** [comment]
I was a considering it. But that would mean i would use numbers, which kist looks garbage

**Comment by uecasm** [comment]
Maybe a UI change?  Select the output block type _first_, which then updates the slots to show the type of block each slot wants (and hides the third slot when unused).  The output slot just stays empty if it's not valid for the inputs, instead of hiding the type buttons.

Might even be able to squeeze in the tooltip words next to the input slots that way (esp. if made purely vertical), but icons are probably simpler.  Albeit a bit more complex to implement in a tooltip.

**Comment by marchermans** [comment]
> Maybe a UI change? Select the output block type _first_, which then updates the slots to show the type of block each slot wants (and hides the third slot when unused). The output slot just stays empty if it's not valid for the inputs, instead of hiding the type buttons.
> 
> Might even be able to squeeze in the tooltip words next to the input slots that way (esp. if made purely vertical), but icons are probably simpler. Albeit a bit more complex to implement in a tooltip.

Was considered and rejected, we try to stay within the current way of doing things with regards how Mojang develops its blocks and systems, with the goal of keeping the mod relatively small.

I will see what I can do, and I can agree that there is a mismatch between the UI of the cutter and the tooltips of the blocks etc, but it is not a bad design or a weird system.

**Comment by SivartMcDorf** [comment]
how about just a standard arrangement then for all three menus if text length is the issue maybe try to find shorter descriptive words.   As long as all 3 use the same arrangement I think it would be OK so if the architect cutter and teach window both followed the exact same pattern as the tooltip that would be more clear.  The architect tool though I have created a lot of incorrect items I will never use trying to figure out what goes in each block.  For shortened terms, you could use something like
Materials
"Main" for main
"Base" for support
"Cover" for cover

All I am asking for is consistent ease of use.  I know it makes sense to you guys from a programming standpoint and because you designed it. I have done UI's and programming about 30 years back and what makes sense to the programmer isn't always intuitive to the general masses.  When I get asked by almost every new person on my server trying out minecolonies how to use the items and I have trouble explaining it to me that would indicate an issue.  And I admit I am old and at times slow keeping up now that VCR's aren't a thing anymore, but I have trouble figuring this out.

**Comment by marchermans** [comment]
> how about just a standard arrangement then for all three menus if text length is the issue maybe try to find shorter descriptive words. As long as all 3 use the same arrangement I think it would be OK so if the architect cutter and teach window both followed the exact same pattern as the tooltip that would be more clear. The architect tool though I have created a lot of incorrect items I will never use trying to figure out what goes in each block. For shortened terms, you could use something like Materials "Main" for main "Base" for support "Cover" for cover
> 
> All I am asking for is consistent ease of use. I know it makes sense to you guys from a programming standpoint and because you designed it. I have done UI's and programming about 30 years back and what makes sense to the programmer isn't always intuitive to the general masses. When I get asked by almost every new person on my server trying out minecolonies how to use the items and I have trouble explaining it to me that would indicate an issue. And I admit I am old and at times slow keeping up now that VCR's aren't a thing anymore, but I have trouble figuring this out.

This would work, if not all blocks would be completely different and things like base, main or cover might work for shingles but not for timberframes, doors etc.

**Comment by SivartMcDorf** [comment]
understood I have mainly used it for the shingles so that is my experience with it.  The only doors I made were an accident as I thought they were the same as the vanilla doors or interchangeable with them.  Maybe a guide button like on the builders hut or something then?

**Comment by marchermans** [comment]
Nope not possible DO is explicitly designed to not use anything from Minecolonies, it is a standalone mod on purpose, because this was explicitly asked for.

That said I want to look into this eventually, untill then JEI is your friend

**Comment by SivartMcDorf** [comment]
I am fine with the new addition of the recipe tool in crafters.
