### ISSUE TITLE
Player-less block placement of panels seems to cause fatal crash

### ISSUE THREAD

**Issue by switchbadger** [ldtteam/Domum-Ornamentum#255]
**Test case**
When a Rannuncarpus from Botania attempts to place a panel from Domum Ornamentum, your world will crash.
World save data cannot be reloaded at this point.
This has been reliably recreated.

**Recovery**
Enable the removeErroringEntities option in your Forge server config, and reload your world.
(Then stop your world and disable that setting again, as per advice given to me.)

**Work around (for this particular case)**
The Botania server config files allow you to blacklist particular items or mods with regards to what the Rannuncarpus is allowed to interact with. Blacklisting "domum_ornamentum:panel" items seems to prevent this particular case. I've added all "domum_ornamentum" blocks to the blacklist until such a time as I can test all of the blocks from DO.

**Suspicions from the bug tester/server admin**
I think that the placement of a panel is trying to reference the orientation of how that panel should be placed, as determined by the player's aim at the target block face, but in a player-less placement scenario it throws a null pointer exception.

**Suggestion**
If my suspicions above are correct, I would suggest a default orientation for panels to be placed in the event of a player-less placement scenario.
This may prevent similar issues with any mod that also allows for player-less, automated placement of blocks.

-----------------------------------------------

[crash-2024-08-28_10.16.44-server.txt](https://github.com/user-attachments/files/16785305/crash-2024-08-28_10.16.44-server.txt)

**Comment by switchbadger** [comment]
Also a shoutout to the DO devs.
Your mod is friggen cool and my server's builder was distraught at the prospect of me having to remove your mod from my modpack.
Thank you for your excellence!

**Comment by someaddons** [comment]
fixed in the newest
