### ISSUE TITLE
Optifine error

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Domum-Ornamentum#29]
Logs: https://gist.github.com/Nightenom/eb3c16ddbc3d1b8c2803c1ee78b0c318

Desc: after changing shaders latest.log gets spammed with error message, till first shader change everything is fine, after that you have to restart the game to make do blocks working again

**Comment by marchermans** [comment]
No clue, Optifine is not supported anyway, i tried to fix this without it being in my dev env but was not able to, closing since this is out of scope.
