### ISSUE TITLE
BSL shaders break textures

### ISSUE THREAD

**Issue by epicyeeto** [ldtteam/Domum-Ornamentum#30]
![2022-02-10_22 19 52](https://user-images.githubusercontent.com/73504007/153532844-6762e8ac-150e-40e7-82bd-71d8e8236db1.png)

OpenGL: 1281 error

**Comment by niceguynate** [comment]
Repeatable with and without optifine, using most up to date version as of 2/12

**Comment by marchermans** [comment]
This is not really something we can fix.
We follow the MinecraftForge rendering engine and it's pipeline.
