### ISSUE TITLE
Solid blocks should not be translucent render type

### ISSUE THREAD

**Issue by Nightenom** [ldtteam/Domum-Ornamentum#31]
a) performance hit (camera based sorting + blending for non-translucent blocks, iirc solid/cutout has blending turned off)
b) shaders being stupid and bigger performance hit, example: https://discord.com/channels/472875599422291968/472879361800929290/943173427416694794
problematic code: https://github.com/ldtteam/Domum-Ornamentum/blob/version/latest/src/main/java/com/ldtteam/domumornamentum/client/event/handlers/ModBusEventHandler.java#L62

The problem is how to either define rendertype per block instance or how to connect two instances of same block (one cutout, one translucent) together in way that end-user can't see

Side note: if not yet possible PR into forge: allow block to use more rendertypes -> block rendering methods would need rendertype based variant

**Comment by marchermans** [comment]
Not solveablke at the moment without more fancy systems. Impact is negligent.

**Comment by marchermans** [comment]
Basically the render type selector does not give you the block entity data. You would need to generate a new model per render type like i am doing with candb which is possible, but not something i am planning to add since our current system does not support discarding vertices from the geometry.

As such closing as technically not feasible.

**Comment by marchermans** [comment]
Hit me up on discord night if you want to talk about this.

**Comment by leagris** [comment]
Illustrate one of the side-effects when rending solid blocks in pass-2 (translucent). The "I need attention" icon is overlaid by domum_ornamentum solid blocks rendering as translucent: ![screenshot](https://i.imgur.com/AFnsjYP.png)
