### ISSUE TITLE
Cactus Stairs

### ISSUE THREAD

**Issue by SerranoPancake** [ldtteam/Domum-Ornamentum#32]
Cactus stairs top texture not consistent with side or front.
Vanilla wooden stairs texture lines always run East/West no matter rotation.
Cactus stairs top texture rotates with stairs, but sides do not.
![image](https://user-images.githubusercontent.com/20136617/154599239-fa58f70d-cf7a-4ddd-99f7-22e7bddedcbb.png)
![image](https://user-images.githubusercontent.com/20136617/154599272-8f801fd1-10d8-4c49-aee6-0fbb7e0a2073.png)

**Comment by marchermans** [comment]
Looks like UV rotation is not applied properly...

**Comment by marchermans** [comment]
Fixed in an upcoming release.
