### ISSUE TITLE
Shift-clicking output doesn't check entire inventory for space

### ISSUE THREAD

**Issue by Spazmunki13** [ldtteam/Domum-Ornamentum#34]
I noticed that when shift clicking the output slot in the Architect's cutter, it will only create stacks to fill the hotbar and the 2 bottom right slots of the inventory.

Expected behavior is for it to simply use all resources given and make as many as can fit in the inventory. (In this case, because I tested in creative, it should've filled my entire inventory.)

Mod Versions:
![image](https://user-images.githubusercontent.com/29984387/154811228-016a915e-af88-4433-956b-17619e26b4ba.png)

https://user-images.githubusercontent.com/29984387/154811186-3d563b46-781a-4b7c-9065-62d3d9f5f9c0.mp4

**Comment by marchermans** [comment]
Hmm, this is likely limited to the crafting count logic, I understand the issue, but not sure I can do much here, should however be a simple fix if I can fix it.

**Comment by quietust** [comment]
Strangely, it doesn't even consider the entire hotbar - it only fills the first 7 slots (along with the 2 bottom-right slots of the inventory).

Since MineColonies buildings tend to require large quantities of these sorts of blocks, this bug makes it extremely frustrating to craft them.
