### ISSUE TITLE
Texture Errors with any shaders

### ISSUE THREAD

**Issue by chanSyy** [ldtteam/Domum-Ornamentum#36]
I have texture errors with any shader.
I try 4 different shaders
Can i fix it and play with shaders somehow?

![2022-02-27_22 41 50](https://user-images.githubusercontent.com/100537176/155899249-6331568a-fc04-468a-933a-8f8aefd67d27.png)
![2022-02-27_22 42 36](https://user-images.githubusercontent.com/100537176/155899251-7fa20f38-8fec-4f10-9843-5e9793c64ddf.png)

**Comment by marchermans** [comment]
Not that we are aware of.
DO Creates normal forge models and marks them as such.

It is very likely that the shader which you are using is just not capable of reading those custom models.
