### ISSUE TITLE
Bug:JEI's recipe menu doesnt stop at the selected recipe

### ISSUE THREAD

**Issue by pantsguyapp** [ldtteam/Domum-Ornamentum#39]
Demonstration: click the recipe button on the random shingle selecting and see that the recipe menu is also jumping over different recipes.

**Comment by OrionDevelopment** [comment]
I don't understand, for me JEI behaves exactly as intended.

**Comment by OrionDevelopment** [comment]
Can you elaborate on your issue? Potentially with a recording of what you are seeing?
