### ISSUE TITLE
Custom slabs kind of broken

### ISSUE THREAD

**Issue by devjavu7** [ldtteam/Domum-Ornamentum#46]
When you place a custom slab on top of a different custom slab, it will convert to the one placed last. When breaking a block of two slabs you also only get one slab back.
Version: 1.18.1-1.0.39

**Comment by marchermans** [comment]
@Raycoms We missed this during testing.
Any idea how to handle this?
Likely would require a custom "double" slab model / block so that we can render the textures right?

**Comment by Raycoms** [comment]
We have two solutions, either a custom double slab model, or we block the player from combining two slabs and allow only combing two of the same

**Comment by marchermans** [comment]
Personally I don't care.
Cursory glance says they are about the same amount of work...

**Comment by someaddons** [comment]
I'd disallow it, there are issues with too many DO blocks due to buffer sizes so putting two together as a normal block is sub-optimal

**Comment by marchermans** [comment]
> I'd disallow it, there are issues with too many DO blocks due to buffer sizes so putting two together as a normal block is sub-optimal

That is just completely not true.....
We optimized the block models already and the buffers are massive....

**Comment by Raycoms** [comment]
We had one of our schematics crashing

**Comment by marchermans** [comment]
It should not happen anymore....

**Comment by Raycoms** [comment]
They are a bit less complex, but still too much for mojang to handle a lot of them apparently

**Comment by Raycoms** [comment]
We could mixin the max size =P As it's just arbitrary isn't it?

**Comment by marchermans** [comment]
No, they actually automatically grow the buffer....
So it is technically not even possible to run out....

Until, somebody shows me how they did it, I blame it on something the user installed or did to cause it to crash.

**Comment by marchermans** [comment]
Fixed in an upcoming release.

**Comment by WenXin20** [comment]
This also seems to be an issue in 1.19.2 as well
