### ISSUE TITLE
False texture rotation

### ISSUE THREAD

**Issue by devjavu7** [ldtteam/Domum-Ornamentum#48]
All trapdoors, doors and fence gates get their texture wrong when opened/closed. Door and trapdoor textures also ignore on which side the hinge is.
Version: 1.18.1-1.0.39

**Comment by marchermans** [comment]
Okey that might need an update then so that the blockstate produces the correct model.

**Comment by marchermans** [comment]
I tested this out.
For the handles new models will need to be added,
but the texture rotation in it self is not fixable.

**Comment by Imrielle** [comment]
> I tested this out. For the handles new models will need to be added, but the texture rotation in it self is not fixable.

The texture rotation is due to the models themselves, and they will be fixed reasonably soon. School ends next week so I should have far more free time to fix these, and its the number one priority on my ToDo list. :)

**Comment by marchermans** [comment]
No, I talked to ray about this.
The actual rotation of the texture: Trapdoor from log -> open trapdoor texture changes is not fixable.
This is not related to the models or any other thing. DO generates the models from the facing that the face is on, this is by definition not fixable.
