### ISSUE TITLE
A tool to break the blocks 

### ISSUE THREAD

**Issue by JackMcNaughton** [ldtteam/Domum-Ornamentum#60]
- Minecraft Version: 1.18.2
- MineColonies Version:  1.0.808 ALPHA
- Related Mods and their Versions: Domum Ornamentum 1.0.50-ALPHA

## Is your feature request related to a problem?
It is annoying when particular building blocks do not have a tool to break them with for example the Pillar and panels do not say there is a good tool to break the and it takes roughly 4.5 seconds. The Shingles, however, based on my testing, seem to be able to be broken with an axe no matter the material. 

## Enhancement or Change description
I thought that since there are 16 million combinations for the different blocks, it was unreasonable to figure out the right tool in each case. I thought you could by default make it be broken with a pickaxe or simply make a new item call it the Architect Hammer or something else and be able to right-click the block to allow it to insta break. Particular types of blocks could use different tools, as in do not care about the material.
### Notes or related things
I understand this mod is an addition to mine colonies, but I think the blocks are so cool to play with outside of simply mine colonies, and would be cool if you could make it easier to break them.
---
## Viewers

* Add a thumbs-up to the change request to vote for it. This helps the request become more visible to the team and doesn't clutter the comments.
* Add a comment if you have any insights or background information that isn't already part of the conversation.

**Comment by Veranidae** [comment]
it seems the axe is the right tool, at least for the panels. i'm using the one probe and although it _says_ there's no designated tool, when i hold the axe it changes to a check mark and the block seems to break faster
