### ISSUE TITLE
Block highlight causes transparency

### ISSUE THREAD

**Issue by Jkosio23** [ldtteam/Domum-Ornamentum#61]
mc version 1.18
DO version1.0.50-alpha
https://blockshot.ch/Epwm

**Comment by Jkosio23** [comment]
https://blockshot.ch/O3RG

**Comment by f0kx** [comment]
https://imgur.com/a/PM2saQd

**Comment by marchermans** [comment]
The block highlight is not controlled by DO. Technically these blocks are transparent... Which is not really something I can control as of yet.
