### ISSUE TITLE
Framed block only show up as dark oak blocks.

### ISSUE THREAD

**Issue by XxThatOneKid2005xX** [ldtteam/Domum-Ornamentum#68]
When I was playing on creative to check out the mod, (version 1.18.1 alpha 0.49 through versions from December 2021,) I noticed that all the framed blocks show up as Framed Dark Oak Blocks and cycle through all the different framed blocks, so if you try to look up Framed Oak Blocks they don't show up even though they are in the game. I think this has to do with the JEI issue, but that's just speculation.

**Comment by XxThatOneKid2005xX** [comment]
Screenshot
https://user-images.githubusercontent.com/110262415/181845097-3da3ac0a-65bf-413a-a697-56d4a85faaf1.png
Screenshot 2
https://user-images.githubusercontent.com/110262415/181845109-98e7f33a-efbc-4586-a2b2-1951bd301c0c.png

**Comment by Raycoms** [comment]
Yeah, there are too many variants to display. You have to check them out in the cutter itself

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Rattenjunge** [comment]
I have the same issue. I need framed spruce planks.
![grafik](https://user-images.githubusercontent.com/26927982/183259438-9878a04f-578c-4fb0-a895-33b30981c2d5.png)
but there are just the Dark Oak ones and not even they have an image or a craft recipe.
![grafik](https://user-images.githubusercontent.com/26927982/183259558-0f5e9ea2-56ab-4a0d-8108-587596538501.png)

**Comment by MotionlessTrain** [comment]
> I have the same issue. I need framed spruce planks.
> ![grafik](https://user-images.githubusercontent.com/26927982/183259438-9878a04f-578c-4fb0-a895-33b30981c2d5.png)
> but there are just the Dark Oak ones and not even they have an image or a craft recipe.
> ![grafik](https://user-images.githubusercontent.com/26927982/183259558-0f5e9ea2-56ab-4a0d-8108-587596538501.png)

The same answer applies: There are over 6 million combinations of blocks possible with the architect's cutter. Hence they only show one, cycling through the various materials.
In order to find out which materials you need, check the tooltip of the requested item and put those blocks in the architect's cutter

**Comment by marchermans** [comment]
If you are in creative this normal.
There is no save way for the system to display all, so in creative it displays a magic variant which randomly changes the values of the materials. If you need a specific variant, you need to craft it.

**Comment by JQE** [comment]
I am trying to complete a build, and its asking for framed dark oak planks. I am NOT in creative.

When i look at the tooltip, it is whatever it was cycling by at the time. It doesn't show me what the Builder wants. I have no idea how to fullfill it if i don't know what it is....

It says Framed Dark Oak Planks in the description. Other blocks have been fine. This is for building a level 2 Tavern birch style.

**Comment by MotionlessTrain** [comment]
That is a schematic issue in minecolonies, which has been fixed already.
Please update minecolonies to the latest alpha version

**Comment by JQE** [comment]
thanks i will try that.

EDIT: That worked. Thanks again.
