### ISSUE TITLE
Create mod not generating tags for all of its various stones.

### ISSUE THREAD

**Issue by Kakiharu** [ldtteam/Domum-Ornamentum#70]
I ran into this while trying to use Asurine Stone and found out that you cannot put them into the Architects cutter. I didnt know if I should put this on their issues page or here. Seeing how create is growing pretty fast it and starts showing up in more packs it would be great to be able to use these blocks.

**Comment by marchermans** [comment]
Report this to create please.
They should decide to what tags there blocks are added.
