### ISSUE TITLE
Feature Enhancement: Multiple panels per block used.

### ISSUE THREAD

**Issue by kedamono** [ldtteam/Domum-Ornamentum#75]
Currently, we only get one panel per block. As I understand it, it's because panels are based on trapdoors. Still, while they have the trapdoor attributes: top, bottom, open, etc., they are not trapdoors. Because they are 1/4 of a block thick, it would make sense that you would get 4 panels per block. If you want to account for waste in manufacturing them, 3 panels per block. Otherwise, they become fairly expensive as compared to slabs, which are 2 per block.

**Comment by Yourname942** [comment]
Do panels work like Applied Energistics 2's cable facade?https://appliedenergistics.github.io/features/decorative-blocks/cable-facade

**Comment by Thodor12** [comment]
> Do panels work like Applied Energistics 2's cable facade?https://appliedenergistics.github.io/features/decorative-blocks/cable-facade

No, but that is beside the discussion of this issue, this is related to the recipe of creating these panels in the first place.

**Comment by MotionlessTrain** [comment]
Speaking of which, that has already been implemented. You now get 4 panels per block

**Comment by Yourname942** [comment]
Oh sorry, I misinterpreted the OP's statement.
