### ISSUE TITLE
Missing Slab Textures (Doubleslabs Incompatibility)

### ISSUE THREAD

**Issue by DorkMuffin** [ldtteam/Domum-Ornamentum#79]
Slabs otherwise work finem and this is more of a feature request than anything, but every custom slab has a blank (missing) texture when placed vertically (with Doubleslabs) or when doubled up with any other slab, custom or not. Since I have literally no experience with java and these sorts of things, I thought I'd post it here first since otherwise Doubleslabs works fine, so I figure its some sort of material/model id mismatch.

**Comment by marchermans** [comment]
I looked into this, and it is sadly not something we can offer.
