### ISSUE TITLE
Cannot craft paper walls

### ISSUE THREAD

**Issue by uecasm** [ldtteam/Domum-Ornamentum#8]
Using 1.0.9-ALPHA.

There does not appear to be any combination of items that can be placed in the architect's cutter that will display the option to craft a `blockpaperwall`.

**Comment by uecasm** [comment]
The above wasn't quite true -- there are _some_ items that work, but not the ones you'd expect (and not the ones that are used in MineColonies schematics).

It looks like the main problem is that #6 removed the option to use `BlockTags.PLANKS` (among a lot of other things) for the paper wall frame.  Probably all of those removals need to be inspected to see if they were intended or accidental.  (And if they were intended, then the MineColonies schematics need fixing.)

**Comment by Raycoms** [comment]
Was not intended to remove them from this. Should re-add all those that are not in default here
