### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by chanSyy** [ldtteam/Domum-Ornamentum#80]
No textures of all blocks. Can`t play normal with this.
![2022-08-23_01 10 49](https://user-images.githubusercontent.com/100537176/186027707-b21b946e-5777-4e41-9f6f-b9d4090db43e.png)
![2022-08-23_01 11 28](https://user-images.githubusercontent.com/100537176/186027713-2a7fef98-0967-490e-81eb-6fc0a6e9e93e.png)

**Comment by MotionlessTrain** [comment]
If you just enabled/disabled/switched shaders, you need to restart minecraft to see the blocks again properly

**Comment by chanSyy** [comment]
> If you just enabled/disabled/switched shaders, you need to restart minecraft to see the blocks again properly

oh thanks man, i just play with "minecolonies", and with shaders can`t see what building im placing so i disable shaders. Thanks again
