### ISSUE TITLE
[1.19.2] Attempting to load Shingles in any way leads to an immediate crash

### ISSUE THREAD

**Issue by Wafiiee** [ldtteam/Domum-Ornamentum#83]
Loading in creative inventory, giving myself the item or anything similar immediately causes a crash.
Giving myself the item renders the world unresponsive on loading, and leads to a quick crash within 30 seconds, thus completely breaking the world permanently. Only Shingles specifically results in a crash, however have not checked whether Shingles Slabs do the same thing. 

Can test by giving self the item, or typing in "Shi" in creative inventory (or manually scrolling).

Crash has happened every time I've tried.

Crash report attached. Have used both the most recent version (1.19-0.60-ALPHA) and (1.19.2-0.59-ALPHA), crash occurs on both for the same reason.

[crash-2022-09-11_13.20.25-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9541708/crash-2022-09-11_13.20.25-client.txt)

**Comment by LexiLeeRanson** [comment]
This may come a little late, but the issue I believe is to do with optifine. There may be a way to fix it in the optifine config. I fixed the issue by removing optifine from my game. 

It might be something to do with OpenGL not liking the blocks but I have no experience with it or Java so could be something completely different.

**Comment by marchermans** [comment]
This is caused by optifine, which is incompatible with Forge 1.19
