### ISSUE TITLE
Game crash When looking in jei due to baked model

### ISSUE THREAD

**Issue by PickleDre** [ldtteam/Domum-Ornamentum#84]
[crash-2022-09-14_12.43.15-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9565985/crash-2022-09-14_12.43.15-client.txt)

**Comment by angeerey** [comment]
I am having the extra same problem, however, I was using optifine alongside these mods and I believe that was causing my game to crash.

**Comment by marchermans** [comment]
This is an issue with optifine.
Please make sure you run an optifine version which is compatible with the latest Forge!
