### ISSUE TITLE
[Minor Bug 1.18.2] Blocks from Modded Materials have invisible frames

### ISSUE THREAD

**Issue by INooBTooMuch** [ldtteam/Domum-Ornamentum#85]
Currently I only tested 2 mods ([Forbidden and Arcanus](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus) and [Supplementaries](https://www.curseforge.com/minecraft/mc-mods/supplementaries)) but the frames (the black outline of the block when the player looks at it) are invisible/see-through.

![2022-09-23_16 43 02](https://user-images.githubusercontent.com/107572028/191975629-08d2eefc-7558-48c2-8df6-00c0ec04686f.png)
![2022-09-23_16 46 41](https://user-images.githubusercontent.com/107572028/191975654-ffeb5427-a2a9-4a73-b545-b2049e238f48.png)
![2022-09-23_16 48 12](https://user-images.githubusercontent.com/107572028/191975672-a36eb49c-9d50-4a1e-bc5b-724221e467c6.png)

**Comment by marchermans** [comment]
Interesting I will need to investigate

**Comment by marchermans** [comment]
Not reproduceable.
Is it still an issue?

**Comment by INooBTooMuch** [comment]
Yes its still there.
(Also the arcane crystal blocks seem to be transparent now, I don't know if that is intentional.)
![2022-11-06_14 13 37](https://user-images.githubusercontent.com/107572028/200170097-b910311f-ceb1-49b0-a441-d6e85310563d.png)

**Comment by marchermans** [comment]
Is it just with modded blocks?

**Comment by Raycoms** [comment]
The timberframes afaik are on purpose just 99% of blocks size, to make sure that the block behind them renders, shadows work properly etc

**Comment by INooBTooMuch** [comment]
I just saw that there are 2 alpha versions above the one I am playing, I will test and see if it happens on those (I was in 1.0.50-ALPHA)

**Comment by INooBTooMuch** [comment]
> Is it just with modded blocks?

It still happens with vanilla oak planks (oak , dark oak, spruce and not only the doors)(domum_ornamentum-1.18.2-1.0.55-ALPHA-universal.jar)

![2022-11-07_15 27 07](https://user-images.githubusercontent.com/107572028/200323647-696b4146-9751-43a2-ae54-4a2a0945f1d4.png)

(the missing texture is when I tried some of the planks from [Chipped](https://www.curseforge.com/minecraft/mc-mods/chipped))

**Comment by Sindin-Luckstone** [comment]
I am also having this issue at this time. Its only ever the block your aiming at but it results in the build looking funky.
