### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by gaia3175** [ldtteam/Domum-Ornamentum#86]
I'm getting the following error message: "Failed to load correctly. Java.Lang.NoClassDeffFoundError: net/minecraftforge/registries/IForgeRegistryEntry"

**Comment by marchermans** [comment]
Are you on fabric?

**Comment by gaia3175** [comment]
I'm on Forge

**Comment by marchermans** [comment]
It looks like you are using a version of the mod on an unsupported game version, could you upload a log please?

**Comment by gaia3175** [comment]
[latest.log](https://github.com/ldtteam/Domum-Ornamentum/files/9641437/latest.log)

**Comment by marchermans** [comment]
I will the latest log as well as the debug log and the generated crash report mentioned in said log please. Thank you!

**Comment by gaia3175** [comment]
[latest.log](https://github.com/ldtteam/Domum-Ornamentum/files/9641487/latest.log)
[crash-2022-09-25_14.17.47-fml.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9641488/crash-2022-09-25_14.17.47-fml.txt)

I can't find a debug log.

**Comment by marchermans** [comment]
You are using the 1.18.2 version of the mod on 1.19.2.
That won't work.
Update the mod.

**Comment by gaia3175** [comment]
OK, thanks.
