### ISSUE TITLE
[1.19.2] All framed blocks using planks of any vanilla minecraft style are invisible using any bdcraft texture pack

### ISSUE THREAD

**Issue by PapaSteeni** [ldtteam/Domum-Ornamentum#87]
Title says it all. Framed blocks using vanilla planks (any kind) work perfectly with standard minecraft textures. As soon as you switch ressourcepack these framed blocks become invisible. No error in the logs whatsoever. See images. Same texturepack in minecraft 1.18 does not have this problem. Tried every resolution (16X up to 128X for MC1.19.x and 128X for 1.18.x) with the same results.

![2022-09-26_21 39 52](https://user-images.githubusercontent.com/5794079/192367365-7efab1d6-9306-4f74-ba2c-a809dd6c3472.png)
![2022-09-26_21 40 26](https://user-images.githubusercontent.com/5794079/192367409-709d35ae-8724-4a07-9562-538960b4fe04.png)

**Comment by Moobien** [comment]
have you spoken to the Sphax team about this? I have yet to see this with the many other resource packs I use, so it seems relatively limited to Sphax so I think its on them to fix.,

**Comment by andybish** [comment]
not sure if this was OP or someone else, but this thread has a response from a bdcraft web admin. posters there seem to think it's something to do with missing json files? https://bdcraft.net/community/help-centre-f4/domum-ornamentum-blocks-are-invisible-using-bdcraf-t8874.html

**Comment by Moobien** [comment]
The problem is that it works fine in every other resource pack I have used. This is why the issue has to be on their end.

**Comment by marchermans** [comment]
Yeah I am not aware of anything on our end that prevents this.
Looks like they mess with the textures.....
Nothing really that I can do about it.
