### ISSUE TITLE
Crashed when I opened my inventory with JEI installed

### ISSUE THREAD

**Issue by robbenrose** [ldtteam/Domum-Ornamentum#88]
[crash-2022-09-27_10.19.06-client.txt](https://github.com/ldtteam/Domum-Ornamentum/files/9657426/crash-2022-09-27_10.19.06-client.txt)

**Comment by Talyda** [comment]
You're using optifine. Try without. It's not supported in 1.19 yet

**Comment by MotionlessTrain** [comment]
Duplicate of #84
