### ISSUE TITLE
ARchitect table not excepting Blocks

### ISSUE THREAD

**Issue by Nadu1988** [ldtteam/Domum-Ornamentum#91]
I have build myself a Modpack for me  and my Brother to play.

But we couldnt put any block in the architect table. After hours of searching and deleting mods one after another i found out that there is a problem with forbidden and arcanus or vallhelsia core.

I use the newest forge 43.1.32
blockui-1.19-0.0.60-ALPHA.jar
structurize-1.19.2-1.0.449-ALPHA.jar
domum_ornamentum-1.19-1.0.60-ALPHA-universal.jar
minecolonies-1.19.2-1.0.1054-ALPHA.jar
multi-piston-1.19-1.2.16-ALPHA.jar
valhelsia core - 0.4.0
forbidden and arcanus-1.19.2-2.10 beta 

Im not sure why i cant work with the table or see any of the recipes in jei as long as i have  forbidden and arcanus and 
the valhelsia coer in the pack but thought it could help. 

Sry for the Bad grammar and english.
Its a great mode giving many possibilities Thx for all your work

**Comment by marchermans** [comment]
Please report this to Forbidden and Arcanus.
It is caused by that mod.
