### ISSUE TITLE
Causing a crash when scrolling though jei

### ISSUE THREAD

**Issue by timingplanet** [ldtteam/Domum-Ornamentum#92]
Mod is causing minecraft to crash when scrolling though jei.
[crasjt.log](https://github.com/ldtteam/Domum-Ornamentum/files/9702571/crasjt.log)

**Comment by Talyda** [comment]
No, optifine is causing a crash. Don't use it.

**Comment by marchermans** [comment]
This is caused by optifine and as of now there is no way to prevent this.
