### ISSUE TITLE
DO blocks with fixed additional textures don't display

### ISSUE THREAD

**Issue by Raycoms** [ldtteam/Domum-Ornamentum#94]
A lot of the doors got iron_block textures for handles, but they don't display

**Comment by Raycoms** [comment]
![image](https://user-images.githubusercontent.com/6438347/194710171-1406af97-e9fe-4447-bce5-63c0f7096aa3.png)
1.18.2 has handles
![image](https://user-images.githubusercontent.com/6438347/194710178-30173900-7bd1-451b-a0e3-13c76f438dd8.png)
doesn't

**Comment by marchermans** [comment]
Fixed in the latest version
