### ISSUE TITLE
Port Manteau Door Renders Incorrectly

### ISSUE THREAD

**Issue by WenXin20** [ldtteam/Domum-Ornamentum#96]
`Domum Ornamentum v1.0.60-alpha`
The only mods installed is JEI and the mods related to Minecolonies

In 1.19.2, the door displays like this in game:

![image](https://user-images.githubusercontent.com/12000593/195964390-ca2cf6a9-e486-438c-ba65-ea43434998c5.png)

but blockbench shows that the door should look like this:

![image](https://user-images.githubusercontent.com/12000593/195964366-5bc13d53-0a3e-4f33-ae65-6a934ee5f5f3.png)

**Comment by marchermans** [comment]
Fixed in the latest version
