### ISSUE TITLE
Valhelsia 5 cant put items into the chisel

### ISSUE THREAD

**Issue by J05HY06** [ldtteam/Domum-Ornamentum#98]
Not sure what mod has incompatibility but hope someone here has more knowledge than me. I cant put any items into the 3 input slots on the architects chisel so i cant craft any blocks from the mod. Playing Valhelsia 5 v5.0.3 with rubidium and oculus installed

**Comment by MotionlessTrain** [comment]
Forbidden and Arcanus is probably the one causing the issues

**Comment by J05HY06** [comment]
seems to be an issue with Forbidden & Arcanus yep

**Comment by marchermans** [comment]
This has been fixed in the latest update of F&A nothing we can do.
